n1 = int(input("Digite um número inteiro: "))
n2 = int(input("Digite outro número inteiro: "))
n3 = float(input("Digite um número real: "))

print("O produto do dobro do primeiro com metade do segundo: ")
print((n1*2) * (n2 / 2))
print("A soma do triplo do primeiro com o terceiro: ")
print((n1*3)+n3)
print("O terceiro elevado ao cubo: ")
print(n3 ** 3)